In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import numpy as np

In [3]:
mylist = [1,2,3]
type(mylist)

list

In [4]:
myarray = np.array(mylist)

In [5]:
type(myarray)

numpy.ndarray

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.linspace(0,10,60)
# Signature:      
# np.linspace(
#     start,
#     stop,
#     num=50,
#     endpoint=True,
#     retstep=False,
#     dtype=None,
#     axis=0,
# )

array([ 0.        ,  0.16949153,  0.33898305,  0.50847458,  0.6779661 ,
        0.84745763,  1.01694915,  1.18644068,  1.3559322 ,  1.52542373,
        1.69491525,  1.86440678,  2.03389831,  2.20338983,  2.37288136,
        2.54237288,  2.71186441,  2.88135593,  3.05084746,  3.22033898,
        3.38983051,  3.55932203,  3.72881356,  3.89830508,  4.06779661,
        4.23728814,  4.40677966,  4.57627119,  4.74576271,  4.91525424,
        5.08474576,  5.25423729,  5.42372881,  5.59322034,  5.76271186,
        5.93220339,  6.10169492,  6.27118644,  6.44067797,  6.61016949,
        6.77966102,  6.94915254,  7.11864407,  7.28813559,  7.45762712,
        7.62711864,  7.79661017,  7.96610169,  8.13559322,  8.30508475,
        8.47457627,  8.6440678 ,  8.81355932,  8.98305085,  9.15254237,
        9.3220339 ,  9.49152542,  9.66101695,  9.83050847, 10.        ])

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.random.rand(5,2)

array([[0.10857839, 0.00193783],
       [0.69533843, 0.54856209],
       [0.92385812, 0.63797315],
       [0.35646203, 0.05693682],
       [0.35530459, 0.8460846 ]])

In [15]:
np.random.randn(2,3)

array([[ 0.52266608,  1.38058989,  1.60063566],
       [-0.09561655,  0.76899986,  2.06312748]])

In [16]:
np.random.randint(0,101,(4,5))

array([[83, 57,  6, 60, 30],
       [12, 66, 98, 47, 34],
       [74, 77, 88, 54, 99],
       [50, 58, 21, 73, 45]])

In [17]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [18]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
randarray = np.random.randint(0,101,10)

In [21]:
randarray

array([ 9, 77, 40,  4, 63, 40, 60, 92, 64,  5])

In [22]:
randarray.max()

92

In [23]:
randarray.min()

4

In [24]:
randarray.argmax()

7

In [25]:
randarray.argmin()

3

In [26]:
randarray.dtype

dtype('int64')

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
arr.shape

(25,)

In [29]:
arr = np.arange(0,11)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr[8]

8

In [32]:
arr[1:5]

array([1, 2, 3, 4])

In [33]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [34]:
arr[:5]

array([0, 1, 2, 3, 4])

In [35]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [36]:
arr[0:5] = 100

In [37]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [38]:
arr=np.arange(0,11)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
slice_of_arr = arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99])

In [43]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [44]:
arr_copy = arr.copy()

In [45]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [46]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [47]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [48]:
arr_2d.shape

(3, 3)

In [49]:
arr_2d[0]

array([ 5, 10, 15])

In [50]:
arr_2d[2]

array([35, 40, 45])

In [51]:
arr_2d[2][2]

45

In [52]:
arr_2d[0][2]

15

In [53]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [54]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [55]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [57]:
bool_arr = arr>4
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [58]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [59]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [61]:
arr-2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [62]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [63]:
arr*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [64]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [65]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
arr.sum()

45

In [67]:
arr.var()

8.25

In [68]:
arr.std()

2.8722813232690143

In [69]:
arr_2d = np.arange(0,25).reshape(5,5)

In [70]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [71]:
arr_2d.sum()

300

In [72]:
arr_2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [73]:
arr_2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])